Repository pycontribs/jira, pull requests merged in 2021-11, with the labels that each got.

#1200 username as default self-hosted field for `current_user()`
  jira/client.py
Labels: bug

#1201 Bugfix/restore cookie auth
  jira/client.py
  tests/test_client.py
Labels: bug

#951 Allow both a comment and a worklog rather than just one or the other when transitioning an issue
  jira/client.py
Labels: enhancement

#1225 Refactor release pipeline
  .github/workflows/jira_server_ci.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  tox.ini
Labels: skip-changelog

#1226 Adopt reusable release-drafter config
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/labels.yml
  .github/workflows/push.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#1227 Shorten GHA pipeline job names
  .github/workflows/jira_ci.yml
  .github/workflows/jira_cloud_ci.yml
  .github/workflows/jira_server_ci.yml
Labels: skip-changelog

#1228 Add final check job
  .github/workflows/jira_ci.yml
Labels: skip-changelog

#1229 Bump test dependencies
  .github/dependabot.yml
  .pre-commit-config.yaml
  constraints.txt
  tox.ini
Labels: skip-changelog

#1232 Fix release pipeline
  .github/workflows/release.yml
Labels: skip-changelog

#1234 More gha fixes
  .github/workflows/release.yml
Labels: skip-changelog

#1235 More gha
  .github/workflows/release.yml
Labels: skip-changelog

#1238 Allow verify option as path to cert in config
  jira/config.py
Labels: feature

#1215 improve ResultList types
  .pre-commit-config.yaml
  jira/client.py
  setup.cfg
Labels: feature

#1216 add token auth to docs, update auth examples file
  docs/examples.rst
  examples/auth.py
  examples/cookie_auth.py
Labels: docs, skip-changelog

#1247 Repair release-drafter config
  .github/release-drafter.yml
Labels: skip-changelog

#1246 Avoid printing parsed json response
  jira/client.py
Labels: bug
