Repository pycontribs/jira, pull requests merged in 2021-07, with the labels that each got.

#1079 Fix broken tests
  jira/client.py
  tests/resources/test_custom_field_option.py
  tests/resources/test_dashboard.py
  tests/resources/test_group.py
  tests/resources/test_issue.py
  tests/resources/test_priority.py
  tests/resources/test_project.py
  tests/resources/test_remote_link.py
  tests/resources/test_resolution.py
  tests/resources/test_security_level.py
  tests/resources/test_user.py
  tests/tests.py
Labels: Status: Ready for Merge, bug

#1080 add API reference links to README to help new devs
  README.rst
Labels: docs, skip-changelog

#1084 use requests.structures.CaseInsensitiveDict directly
  docs/conf.py
  jira/client.py
  jira/resources.py
  jira/utils/__init__.py
  tests/resources/test_attachment.py
Labels: Status: Ready for Merge, chore

#1083 rename MyAny to a more meaningful name
  docs/conf.py
  jira/resources.py
Labels: chore, skip-changelog
