Repository pycontribs/jira, pull requests merged in 2021-06, with the labels that each got.

#1045 make tests more approachable
  README.rst
  jira/exceptions.py
  tests/__init__.py
  tests/conftest.py
  tests/resources/__init__.py
  tests/resources/test_attachment.py
  tests/resources/test_board.py
  tests/resources/test_comment.py
  tests/resources/test_component.py
  tests/resources/test_custom_field_option.py
  tests/resources/test_customer.py
  tests/resources/test_dashboard.py
  tests/resources/test_filter.py
  tests/resources/test_generic_resource.py
  tests/resources/test_group.py
  tests/resources/test_issue.py
  tests/resources/test_issue_link.py
  tests/resources/test_issue_link_type.py
  tests/resources/test_priority.py
  tests/resources/test_project.py
  tests/resources/test_remote_link.py
  tests/resources/test_request_type.py
  tests/resources/test_resolution.py
  tests/resources/test_role.py
  tests/resources/test_security_level.py
  tests/resources/test_service_desk.py
  tests/resources/test_sprint.py
  tests/resources/test_status.py
  tests/resources/test_status_category.py
  tests/resources/test_user.py
  tests/resources/test_version.py
  tests/resources/test_vote.py
  tests/resources/test_watchers.py
  tests/resources/test_worklog.py
  tests/test_client.py
  tests/test_exceptions.py
  tests/test_resilientsession.py
  tests/tests.py
Labels: chore

#1074 Refactor locking of test dependencies
  .pre-commit-config.yaml
  bindep.txt
  constraints.txt
  jira/resilientsession.py
  requirements.txt
  setup.cfg
  test-requirements.in
  test-requirements.txt
  tox.ini
Labels: test

#1086 add jira-version to job matrix
  .github/workflows/jira_server_ci.yml
Labels: skip-changelog, test
