Repository pycontribs/jira, pull requests merged in 2021-10, with the labels that each got.

#1166 fix: rename default branch to main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/dependabot.yml
  .github/workflows/jira_server_ci.yml
  .github/workflows/release-drafter.yml
  Makefile
  README.rst
  docs/index.rst
  setup.cfg
Labels: bug

#1170 chore: bumped linters
  .pre-commit-config.yaml
Labels: skip-changelog

#1171 chore: refresh release drafter config
  .github/release-drafter.yml
  .github/workflows/labels.yml
Labels: skip-changelog

#1151 Change markdown templates to issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: skip-changelog

#1205 lazy load `_fields`, (now called `_fields_cache` for clarity)
  jira/client.py
Labels: feature

#1202 add the `.verify` property correctly
  jira/client.py
Labels: bug
