Repository pycontribs/jira, pull requests merged in 2021-05, with the labels that each got.

#1020 chore: replace cspell with codespell
  .pre-commit-config.yaml
  cspell.json
  jira/resilientsession.py
  package-lock.json
  package.json
  tests/tests.py
  tox.ini
Labels: skip-changelog

#1019 Switch to locked test dependencies
  .fossa.yml
  MANIFEST.in
  requirements.txt
  setup.cfg
  test-requirements.in
  test-requirements.txt
  tox.ini
Labels: enhancement

#1018 Cleanup project badges
  README.rst
Labels: skip-changelog

#1005 Update client.py
  jira/client.py
Labels: bug

#1022 chore: isort imports
  .pre-commit-config.yaml
  docs/conf.py
  examples/basic_auth.py
  examples/basic_use.py
  examples/cookie_auth.py
  examples/maintenance.py
  jira/__init__.py
  jira/client.py
  jira/jirashell.py
  jira/resilientsession.py
  jira/resources.py
  make_local_jira_user.py
  setup.cfg
  setup.py
  tests/test_client.py
  tests/test_shell.py
  tests/tests.py
Labels: chore, skip-changelog

#1021 docs: remove cspell reference in README
  README.rst
Labels: docs, skip-changelog

#893 Example of the email address and API token initialization.
  docs/examples.rst
Labels: docs

#1027 Add publish workflow
  .github/workflows/publish.yml
  Makefile
  README.rst
  tox.ini
Labels: skip-changelog

#1001 Comment Author Name and Time
  docs/examples.rst
Labels: docs

#963 chore(github): adds jira instance type to bug-report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: chore, skip-changelog

#1028 Cleanup tox.ini publish
  tox.ini
Labels: skip-changelog

#1029 More publish fixes
  .github/workflows/publish.yml
Labels: skip-changelog

#1030 Even more release fixes
  .github/workflows/publish.yml
Labels: skip-changelog

#1031 Even more release fixes
  .github/workflows/publish.yml
Labels: skip-changelog

#1032 Run only tox pkg on publish
  .github/workflows/publish.yml
Labels: skip-changelog

#1040 cleaning up most travis references
  README.rst
  jira/exceptions.py
  setup.cfg
  tests/tests.py
Labels: skip-changelog

#1039 adding version to documentation to help out on #1016
  docs/api.rst
  jira/resources.py
  tests/tests.py
Labels: docs

#1038 Fix docstring generation of jira client and minor doc layouting fix
  docs/_static/css/custom_width.css
  docs/conf.py
  docs/examples.rst
  jira/client.py
Labels: docs

#1037 Remove .idea folder as it messes up pycharm checkouts (intelij idea folder structure has changed since end 2017)
  .editorconfig
  .gitignore
  .idea/codeStyleSettings.xml
Labels: skip-changelog

#1023 add typehints and allow google docstrings
  MANIFEST.in
  docs/api.rst
  docs/conf.py
  examples/basic_auth.py
  examples/basic_use.py
  examples/cookie_auth.py
  jira/client.py
  jira/config.py
  jira/exceptions.py
  jira/py.typed
  jira/resilientsession.py
  jira/resources.py
  jira/utils/__init__.py
  setup.cfg
Labels: bug, docs, enhancement

#978 Correct lookup of issuetypes when calling create_issue
  jira/client.py
Labels: Status: Ready, enhancement

#933 fix: group_members
  jira/client.py
Labels: bug, feature

#888 Improve feedback for oauth errors.
  jira/jirashell.py
Labels: enhancement

#1044 Adopt fstrings (flynt)
  jira/client.py
  jira/config.py
  jira/exceptions.py
  jira/jirashell.py
  jira/resilientsession.py
  jira/resources.py
Labels: chore, enhancement

#927 Make user search GDPR compliant
  jira/client.py
Labels: bug, duplicate

#957 Close the file descriptor for add_attachment
  jira/client.py
Labels: bug, enhancement

#1003 Allow expands for retrieval of comments
  jira/client.py
  tests/tests.py
Labels: enhancement

#1053 fix assign issue behaviour and correct watcher functions docstrings
  jira/client.py
  make_local_jira_user.py
  tests/tests.py
  tox.ini
Labels: bug

#1051 fix pickling and hashability
  jira/resources.py
  tests/tests.py
Labels: enhancement

#928 ResilientSession: do not log request data on ConnectionError
  jira/resilientsession.py
  tests/tests.py
Labels: enhancement

#865 Add expand to JIRA.project and JIRA.projects
  jira/client.py
  tests/tests.py
Labels: enhancement
