Repository pycontribs/jira, pull requests merged in 2021-09, with the labels that each got.

#1133 fix TB on RequestType instanciation with raw content (fixes #1130)
  jira/resources.py
Labels: bug

#1144 [RFC] add pyupgrade as pre-commit hook and use --py36-plus
  .pre-commit-config.yaml
  docs/conf.py
  examples/basic_use.py
  examples/greenhopper.py
  examples/maintenance.py
  jira/__init__.py
  jira/client.py
  jira/config.py
  jira/exceptions.py
  jira/jirashell.py
  jira/resilientsession.py
  jira/resources.py
  jira/utils/__init__.py
  make_local_jira_user.py
  tests/conftest.py
  tests/resources/test_attachment.py
  tests/resources/test_component.py
  tests/resources/test_project.py
  tests/resources/test_status_category.py
  tests/resources/test_user.py
  tests/test_client.py
  tests/test_exceptions.py
  tests/test_shell.py
  tests/tests.py
Labels: chore

#1157 Fix JWT QSH generation for urls with repeated parameters
  jira/client.py
  tests/test_qsh.py
Labels: bug

#1139 add PermissionScheme Resource
  jira/client.py
  jira/resources.py
  tests/resources/test_project.py
Labels: feature
