Repository pycontribs/jira, pull requests merged in 2022-03, with the labels that each got.

#1275 Fixing type hint to match documentation for move_to_backlog
  jira/client.py
Labels: bug, enhancement

#1102 Add subscriptable support for PropertyHolder
  jira/resources.py
  tests/resources/test_issue.py
Labels: feature

#1338 Bump linters
  .pre-commit-config.yaml
Labels: skip-changelog

#1339 Revert pyupgrade and mypy for py36 compatibility
  .pre-commit-config.yaml
Labels: dependencies, skip-changelog
