Repository pycontribs/jira, pull requests merged in 2022-11, with the labels that each got.

#1502 Use proper SPDX identifier
  setup.cfg
Labels: bug

#1531 dependabot/merged
  .github/workflows/jira_cloud_ci.yml
  .github/workflows/jira_server_ci.yml
  constraints.txt
Labels: dependencies, skip-changelog

#1551 Updating installation instructions
  docs/installation.rst
Labels: docs, skip-changelog

#1526 Properly parse errorMessage key in error response
  jira/resilientsession.py
  jira/resources.py
  tests/test_resilientsession.py
Labels: bug
