Repository pycontribs/jira, pull requests merged in 2022-07, with the labels that each got.

#1381 Create a devcontainer to ease dev setup
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post_create.sh
Labels: docs, skip-changelog

#1383 Raise `JIRAError` when no user found
  jira/client.py
Labels: bug

#1434 ensure `None` is handled correctly in `search_issues()`
  jira/client.py
  tests/resources/test_issue.py
Labels: bug

#1436 update sphinx to fix builds and update RTD config due to deprecations
  .readthedocs.yml
  constraints.txt
Labels: docs, dependencies, skip-changelog
