Repository pycontribs/jira, pull requests merged in 2022-04, with the labels that each got.

#1145 Locate the exact user by key if there are multiple users returned from query
  jira/client.py
Labels: bug

#1350 Drop py36 py37 add py310
  .github/workflows/jira_server_ci.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  README.rst
  constraints.txt
  docs/conf.py
  docs/contributing.rst
  docs/installation.rst
  pyproject.toml
  setup.cfg
  tox.ini
Labels: feature

#1336 gha: use secrets from cloud environment
  .github/workflows/jira_cloud_ci.yml
Labels: skip-changelog

#1359 use importlib.metadata instead of pkg_resources
  jira/__init__.py
  jira/client.py
  setup.cfg
Labels: feature

#1360 updated `jira.search_issues` default behaviour to include all fields
  jira/client.py
  tests/resources/test_issue.py
Labels: feature

#1351 Remove GreenHopper Resource and fix Agile tests
  docs/api.rst
  docs/examples.rst
  docs/index.rst
  examples/agile.py
  jira/client.py
  jira/resources.py
  tests/resources/test_board.py
  tests/resources/test_issue.py
  tests/resources/test_sprint.py
Labels: bug

#1364 Handle #925 rate limit error
  jira/resilientsession.py
  tests/test_resilientsession.py
Labels: feature
