Repository pycontribs/jira, pull requests merged in 2022-08, with the labels that each got.

#1438 derive attachment fname from BufferedReader object (#1437)
  jira/client.py
  tests/resources/test_attachment.py
Labels: bug

#1442 fix `JIRA.search_issues(json_result=True)` typehint
  jira/client.py
Labels: enhancement, skip-changelog

#1441 Remove confusing/dead code
  jira/resources.py
Labels: enhancement, skip-changelog

#1445 Fix bug preventing use of an int for issuetype in def create_issue
  jira/client.py
  tests/resources/test_issue.py
Labels: bug

#1446 Remove remaining non-f-strings
  examples/maintenance.py
  tests/conftest.py
  tests/resources/test_filter.py
  tests/resources/test_issue.py
  tests/resources/test_project.py
  tests/resources/test_status.py
  tests/resources/test_status_category.py
  tests/test_client.py
  tests/tests.py
Labels: skip-changelog

#1447 allow filter updates when no description returned by Jira
  jira/client.py
  tests/resources/test_filter.py
Labels: bug

#1448 Fix using str as issue type with create_issue when issue type with that name exists in many projects
  jira/client.py
  tests/resources/test_issue.py
Labels: bug, feature

#1450 fix `.add_issues_to_epic()`
  jira/client.py
  tests/resources/test_epic.py
Labels: bug

#1439 Add support for IssueProperty resource
  jira/client.py
  jira/resources.py
  tests/resources/test_issue_property.py
Labels: feature

#1471 Avoid always passing on an empty body even if not given
  jira/resilientsession.py
  tests/test_resilientsession.py
Labels: bug

#1472 add required parameter field 'permissions' to my_permissions method
  jira/client.py
  tests/tests.py
Labels: bug
