Repository pycontribs/jira, pull requests merged in 2022-06, with the labels that each got.

#1387 Add notify to comment
  docs/examples.rst
  jira/client.py
  jira/resources.py
  pyproject.toml
  tests/resources/test_comment.py
Labels: enhancement

#1366 tidy ResilientSession implementation
  docs/conf.py
  jira/client.py
  jira/resilientsession.py
  jira/utils/__init__.py
  tests/test_resilientsession.py
Labels: feature

#1394 Configurable batch size for `JIRA._fetch_pages()` and dependant methods
  constraints.txt
  jira/client.py
  setup.cfg
  tests/conftest.py
  tests/test_client.py
  tests/tests.py
Labels: feature

#1404 extend the examples with a more thorough example for getting attachments from a specific comment
  docs/examples.rst
Labels: enhancement, docs

#1405 improve explanation of exception when two sprints with the same name are found
  jira/client.py
  tests/resources/test_sprint.py
Labels: bug, enhancement

#1395 Add client route for deleting remote links by global (and internal) id
  jira/client.py
  tests/tests.py
Labels: feature
