Repository pycontribs/jira, pull requests merged in 2023-12, with the labels that each got.

#1778 Fix #1774 by updating the Accept value to be valid
  jira/resilientsession.py
Labels: bug

#1748 response.__bool__() returns False for Exception cases, so use "is not None" instead
  jira/client.py
Labels: bug

#1713 Add handling of 503 Service Unavailable retries
  jira/resilientsession.py
  tests/test_resilientsession.py
Labels: bug

#1553 use `template_name` for `create_project()`
  jira/client.py
Labels: bug

#1552 add visibility argument
  jira/client.py
Labels: minor

#1723 feat: add an option to use POST for search_issues
  jira/client.py
  tests/tests.py
Labels: feature

#1780 Do round trip with json dumps and loads to ensure true json params
  jira/client.py
Labels: bug

#1729 support pagination in createmeta methods
  jira/client.py
  tests/test_client.py
Labels: enhancement

#1784 Issue Field and Issue Type object based methods
  jira/client.py
  jira/resources.py
  tests/conftest.py
  tests/resources/test_field.py
  tests/resources/test_issue_type.py
  tests/test_client.py
Labels: enhancement, feature

#1786 fix: small fix for dev docker
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post_create.sh
  tests/conftest.py
  tests/test_client.py
  tox.ini
Labels: bug
