Repository pycontribs/jira, pull requests merged in 2023-06, with the labels that each got.

#1664 Allow the user to override the default signature method
  jira/client.py
Labels: bug

#1676 Update create_project docstring
  jira/client.py
Labels: bug

#1687 Minor nits: Doc updates
  docs/examples.rst
Labels: docs, skip-changelog

#1681 Add rich text example to docs
  docs/examples.rst
Labels: enhancement, docs

#1678 implement SHA fallback behaviour
  jira/client.py
Labels: bug

#1680 Replace imghdr with Pillow's PIL
  constraints.txt
  jira/client.py
  setup.cfg
Labels: enhancement

#1682 Use user_id when adding watcher
  jira/client.py
Labels: bug
