Repository pycontribs/jira, pull requests merged in 2023-01, with the labels that each got.

#1527 Support for the new 'createmeta' API in Jira 8.4+
  jira/client.py
Labels: feature

#1598 fix lint errors and rely on pre-commit and readthedocs GHA
  .github/workflows/jira_server_ci.yml
  jira/resilientsession.py
  pyproject.toml
Labels: skip-changelog

#1599 bump all dependencies
  .pre-commit-config.yaml
  constraints.txt
  setup.cfg
Labels: dependencies, skip-changelog
