Repository pycontribs/jira, pull requests merged in 2023-02, with the labels that each got.

#1605 Get the properties when fetching an Issue
  jira/client.py
Labels: feature

#1593 KeyError: "X-RateLimit-FillRate" fix
  jira/resilientsession.py
  tests/test_resilientsession.py
Labels: bug

#1594 Made create_issue and create_issues consistent to handle multiple issue types with same name
  jira/client.py
Labels: bug

#1396 making docstrings more uniform
  jira/client.py
  jira/config.py
  jira/resources.py
Labels: enhancement, docs, skip-changelog

#1267 Add projectstatuses method to get project statuses (missing endpoint)
  jira/client.py
  tests/resources/test_project_statuses.py
Labels: feature

#1574 [feature] Add support for requests timeout
  jira/client.py
  jira/resilientsession.py
  tests/test_resilientsession.py
Labels: bug, enhancement
