Repository pycontribs/jira, pull requests merged in 2023-05, with the labels that each got.

#1643 Switch from SIGNATURE_RSA to SIGNATURE_HMAC_SHA1
  jira/client.py
  jira/jirashell.py
Labels: feature

#1580 Update the type for issue in add_comment & transition_issue for better type hints
  jira/client.py
Labels: feature

#1631 fix verify not sent with request (#1573)
  jira/resilientsession.py
  tests/test_resilientsession.py
Labels: bug

#1625 clean up some comments
  README.rst
  examples/maintenance.py
  jira/resources.py
Labels: skip-changelog

#1623 reduce code duplication and configure session auth after other config
  jira/client.py
Labels: bug, skip-changelog
