Repository pycontribs/jira, pull requests merged in 2024-01, with the labels that each got.

#1787 Added warning log if issue link type not present
  jira/client.py
Labels: enhancement

#1793 add Release Process doc
  RELEASE.md
Labels: skip-changelog

#1733 More RTD maintenance
  .readthedocs.yml
Labels: bug
