Repository pycontribs/jira, pull requests merged in 2025-03, with the labels that each got.

#2326 enhancement: Add enhanced_search_issues API for Jira Cloud using new search/jql endpoint
  .readthedocs.yml
  jira/client.py
Labels: enhancement

#2328 Fix docstring for Issue_delete() method
  jira/resources.py
Labels: bug

#2330 Add missing pip test dependency
  pyproject.toml
Labels: skip-changelog

#2331 Remove support for python 3.9
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/jira_ci.yml
  .github/workflows/jira_cloud_ci.yml
  .github/workflows/jira_server_ci.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
  constraints.txt
  docs/conf.py
  docs/contributing.rst
  docs/installation.rst
  jira/client.py
  jira/resilientsession.py
  pyproject.toml
  tox.ini
Labels: major

#2327 GHA Maintenance
  .config/constraints.txt
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/workflows/ack.yml
  .github/workflows/jira_ci.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  .taplo.toml
  constraints.txt
  pyproject.toml
  tests/conftest.py
  tests/ruff.toml
  tests/test_unit.py
  tox.ini
Labels: skip-changelog
