Repository pycontribs/jira, pull requests merged in 2025-04, with the labels that each got.

#2322 Don't add empty json from default dictionary to GET payloads to avoid 403 from jira API.
  jira/resilientsession.py
  tests/test_resilientsession.py
Labels: bug

#1899 Fix docs for `myself`
  jira/client.py
Labels: bug, docs

#1925 Handle when jira is behind a proxy
  jira/resources.py
  tests/resources/test_issue.py
Labels: enhancement

#1939 Expand comments method to include all available API options
  jira/client.py
  tests/resources/test_comment.py
Labels: enhancement

#2334 Allow users to search issues without retrieving fields
  jira/client.py
Labels: minor

#2335 Logging=False is not honored in _create_oauth_session #1777
  jira/client.py
Labels: bug

#2339 Fix CI GitHub Action Workflow
  .github/workflows/jira_ci.yml
  .github/workflows/jira_cloud_ci.yml
  .github/workflows/jira_server_ci.yml
Labels: skip-changelog

#2342 refactor: restructure release workflow to include artifact upload and download steps with the correct token
  .github/workflows/release.yml
Labels: skip-changelog

#2343 fix: update PyPI publishing environment configuration in release.yml
  .github/workflows/release.yml
Labels: bug

#2344 fix: update tag regex pattern in pyproject.toml for version matching
  pyproject.toml
Labels: bug

#2337 Enable devel testing pipeline
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#2347 fix: fixes #2346 fields input argument for search should not change behaviour
  jira/client.py
Labels: bug

#2348 docs: add warning about broken PyPI release and provide temporary installation instructions
  .github/workflows/release.yml
  README.rst
Labels: skip-changelog
